# Generated by Django 5.2.1 on 2025-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='ticket_quota',
            new_name='ticket_quota_125',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='ticket_quota_80',
            field=models.PositiveIntegerField(default=0, help_text='Tickets numériques restants'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('ADMIN', 'Administrateur'), ('CHEF_SERVICE', 'Chef Service Restaurant'), ('MAGASINIER', 'Magasinier'), ('VENDEUR_TICKETS', 'Vendeur Tickets'), ('RESPONSABLE_GUICHET', 'Responsable Guichet'), ('CUISINIER', 'Cuisinier')], max_length=30),
        ),
    ]
