# Generated by Django 5.2.1 on 2025-06-26 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', 'periode__nomPeriode']},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('reservant_pour', 'date', 'periode')},
        ),
        migrations.AddField(
            model_name='reservation',
            name='initiateur',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_initiees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(help_text='Date de la réservation (détermine la semaine ciblée)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='jour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='monapp.jour'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='monapp.periode'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservant_pour',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_beneficiees', to='monapp.etudiant'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='etudiant',
        ),
    ]
