# Generated by Django 5.2.1 on 2025-06-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('reservant_pour', 'date', 'periode', 'jour')},
        ),
    ]
